# Generated by Django 3.1.7 on 2021-03-04 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('point_lng', models.FloatField()),
                ('point_lat', models.FloatField()),
                ('properties_title', models.CharField(help_text='Название точки на карте', max_length=200)),
                ('properties_place_id', models.CharField(help_text='ID точки', max_length=200, unique=True)),
                ('details_title', models.CharField(help_text='Заголовок', max_length=200)),
                ('details_description_short', models.CharField(help_text='Краткое описание', max_length=400)),
                ('details_description_long', models.TextField()),
                ('details_lng', models.FloatField()),
                ('details_lat', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('order', models.SmallIntegerField(default=1)),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.place')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
