# Generated by Django 3.1.7 on 2021-03-05 14:58

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='point_lat',
        ),
        migrations.RemoveField(
            model_name='place',
            name='point_lng',
        ),
        migrations.RemoveField(
            model_name='place',
            name='properties_place_id',
        ),
        migrations.RemoveField(
            model_name='place',
            name='properties_title',
        ),
        migrations.AlterField(
            model_name='place',
            name='details_description_long',
            field=tinymce.models.HTMLField(),
        ),
    ]
