# Generated by Django 3.1.7 on 2021-03-11 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210311_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Файл изображения'),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название фотографии'),
        ),
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.SmallIntegerField(default=1, verbose_name='Номер фотографии в списке'),
        ),
        migrations.AlterField(
            model_name='image',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.place', verbose_name='Место'),
        ),
    ]
