# Generated by Django 3.1.7 on 2021-03-11 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20210311_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='details_description_long',
            new_name='description_long',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='details_description_short',
            new_name='description_short',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='details_lat',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='details_lng',
            new_name='lng',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='details_title',
            new_name='title',
        ),
    ]
