# Generated by Django 3.1.7 on 2021-03-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_remove_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.SmallIntegerField(null=True, verbose_name='Номер фотографии в списке'),
        ),
    ]
