# Generated by Django 3.1.7 on 2021-03-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_auto_20210311_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='filename',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
