# Generated by Django 3.1.7 on 2021-03-11 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210311_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='filename',
        ),
    ]
