# Generated by Django 3.1.7 on 2021-03-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0016_remove_image_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
