# Generated by Django 3.1.7 on 2021-03-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0017_image_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='filename',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
