# Generated by Django 3.1.7 on 2021-03-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210311_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='filename',
            field=models.CharField(blank=True, default=None, editable=False, max_length=200),
        ),
    ]
