# Generated by Django 3.1.7 on 2021-03-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description_short', models.CharField(max_length=400)),
                ('description_long', models.TextField()),
                ('coordinates_lng', models.FloatField()),
                ('coordinates_lat', models.FloatField()),
            ],
        ),
    ]
