# Generated by Django 3.1.7 on 2021-03-03 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210303_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('order', models.SmallIntegerField(default=0, unique=True)),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.place')),
            ],
        ),
    ]
