# Generated by Django 3.1.7 on 2021-03-03 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['order']},
        ),
    ]
