# Generated by Django 3.1.7 on 2021-03-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210311_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='details_title',
            field=models.CharField(help_text='Заголовок', max_length=200, verbose_name='Название места'),
        ),
    ]
