# Generated by Django 3.1.7 on 2021-03-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_image_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='filename',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
